"""Generate the documented NMOS 6502 opcode table (our own implementation)."""
from pathlib import Path

ROWS = '''
00 BRK IMP 01 ORA INX 05 ORA ZP 06 ASL ZP 08 PHP IMP 09 ORA IMM 0A ASL ACC 0D ORA ABS 0E ASL ABS
10 BPL REL 11 ORA INY 15 ORA ZPX 16 ASL ZPX 18 CLC IMP 19 ORA ABY 1D ORA ABX 1E ASL ABX
20 JSR ABS 21 AND INX 24 BIT ZP 25 AND ZP 26 ROL ZP 28 PLP IMP 29 AND IMM 2A ROL ACC 2C BIT ABS 2D AND ABS 2E ROL ABS
30 BMI REL 31 AND INY 35 AND ZPX 36 ROL ZPX 38 SEC IMP 39 AND ABY 3D AND ABX 3E ROL ABX
40 RTI IMP 41 EOR INX 45 EOR ZP 46 LSR ZP 48 PHA IMP 49 EOR IMM 4A LSR ACC 4C JMP ABS 4D EOR ABS 4E LSR ABS
50 BVC REL 51 EOR INY 55 EOR ZPX 56 LSR ZPX 58 CLI IMP 59 EOR ABY 5D EOR ABX 5E LSR ABX
60 RTS IMP 61 ADC INX 65 ADC ZP 66 ROR ZP 68 PLA IMP 69 ADC IMM 6A ROR ACC 6C JMP IND 6D ADC ABS 6E ROR ABS
70 BVS REL 71 ADC INY 75 ADC ZPX 76 ROR ZPX 78 SEI IMP 79 ADC ABY 7D ADC ABX 7E ROR ABX
81 STA INX 84 STY ZP 85 STA ZP 86 STX ZP 88 DEY IMP 8A TXA IMP 8C STY ABS 8D STA ABS 8E STX ABS
90 BCC REL 91 STA INY 94 STY ZPX 95 STA ZPX 96 STX ZPY 98 TYA IMP 99 STA ABY 9A TXS IMP 9D STA ABX
A0 LDY IMM A1 LDA INX A2 LDX IMM A4 LDY ZP A5 LDA ZP A6 LDX ZP A8 TAY IMP A9 LDA IMM AA TAX IMP AC LDY ABS AD LDA ABS AE LDX ABS
B0 BCS REL B1 LDA INY B4 LDY ZPX B5 LDA ZPX B6 LDX ZPY B8 CLV IMP B9 LDA ABY BA TSX IMP BC LDY ABX BD LDA ABX BE LDX ABY
C0 CPY IMM C1 CMP INX C4 CPY ZP C5 CMP ZP C6 DEC ZP C8 INY IMP C9 CMP IMM CA DEX IMP CC CPY ABS CD CMP ABS CE DEC ABS
D0 BNE REL D1 CMP INY D5 CMP ZPX D6 DEC ZPX D8 CLD IMP D9 CMP ABY DD CMP ABX DE DEC ABX
E0 CPX IMM E1 SBC INX E4 CPX ZP E5 SBC ZP E6 INC ZP E8 INX IMP E9 SBC IMM EA NOP IMP EC CPX ABS ED SBC ABS EE INC ABS
F0 BEQ REL F1 SBC INY F5 SBC ZPX F6 INC ZPX F8 SED IMP F9 SBC ABY FD SBC ABX FE INC ABX
'''
def main():
    words = ROWS.split()
    entries = list(zip(words[::3], words[1::3], words[2::3]))
    assert len(entries) == len({e[0] for e in entries}) == 151
    ops = ['ILL'] + sorted({e[1] for e in entries})
    modes = ['IMP', 'ACC', 'IMM', 'ZP', 'ZPX', 'ZPY', 'ABS', 'ABX', 'ABY', 'INX', 'INY', 'IND', 'REL']
    lines = ['// Generated by tools/gen_cpu_decode.py; do not edit.']
    lines += [f"localparam [5:0] OP_{v} = 6'd{i};" for i, v in enumerate(ops)]
    lines += [f"localparam [3:0] M_{v} = 4'd{i};" for i, v in enumerate(modes)]
    lines += ['function [9:0] decode;', 'input [7:0] code;', 'begin', 'case (code)']
    lines += [f"8'h{h}: decode = {{OP_{op}, M_{mode}}};" for h, op, mode in entries]
    lines += ['default: decode = {OP_ILL, M_IMP};', 'endcase', 'end', 'endfunction', '']
    (Path(__file__).resolve().parents[1] / 'rtl/cpu6502_decode.vh').write_text('\n'.join(lines))

if __name__ == '__main__':
    main()
